### ISSUE TITLE
Refactor React examples 

### ISSUE THREAD

**Issue by aitchiss** [aitchiss/up_your_a11y#33]
The React components in this project use the more 'old fashioned' Component declaration style. I'd like to gradually refactor each component into more modern function components (see for example Contact.jsx), and update any use of state etc to use hooks.

Pull requests for this issue can be a single component, or multiple - whatever suits you!

**Comment by metamoni** [comment]
I'd like to get working on this one. Will start with everything in the `components` folder and submit a PR for that, if that's OK.

**Comment by aitchiss** [comment]
Oh yay! That's fantastic @metamoni !
Just take it as far as you like / think sensible 😊 It will be so nice to have your contribution in the project!
